parameters:
    epixa_simple_user.service.user.class: Epixa\SimpleUserBundle\Service\UserService
    epixa_simple_user.validator.authentication.class: Epixa\SimpleUserBundle\Validator\Constraints\AuthenticationValidator

services:
    epixa_simple_user.service.user:
        class: %epixa_simple_user.service.user.class%
        arguments: [ @doctrine.orm.default_entity_manager, %epixa_simple_user.model.user.class% ]

    epixa_simple_user.validator.authentication:
        class: %epixa_simple_user.validator.authentication.class%
        calls:
          - [ setUserService, [@epixa_simple_user.service.user] ]
        tags:
            - { name: validator.constraint_validator, alias: epixa_simple_user_validator_authentication }