simpleuser_auth_annotations:
    resource: "@EpixaSimpleUserBundle/Controller/AuthController.php"
    type:     annotation

simpleuser_login_check:
    pattern: /login_check

simpleuser_logout:
    pattern: /logout