EpixaTalkfestBundle:
    resource: "@EpixaTalkfestBundle/Resources/config/routing.yml"

EpixaSimpleUserBundle:
    resource: "@EpixaSimpleUserBundle/Resources/config/routing.yml"

# EpixaUserBundle:
#     resource: "@EpixaUserBundle/Resources/config/routing.yml"

# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#     prefix: /fos_user

# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: /fos_user/profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /fos_user/register

# fos_user_resetting:
#     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#     prefix: /fos_user/resetting

# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /fos_user/change-password