security:
    acl:
        connection: default

    providers:
        epixa_simpleuserbundle:
            id: epixa_simple_user.service.user

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: epixa_simpleuserbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/add$, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN