parameters:
    talkfest.service.category.class: Epixa\TalkfestBundle\Service\CategoryService
    talkfest.service.post.class: Epixa\TalkfestBundle\Service\PostService
    talkfest.service.comment.class: Epixa\TalkfestBundle\Service\CommentService

services:
    talkfest.service.category:
        class: %talkfest.service.category.class%
        arguments: [@service_container]
    talkfest.service.post:
        class: %talkfest.service.post.class%
        arguments: [@service_container]
    talkfest.service.comment:
        class: %talkfest.service.comment.class%
        arguments: [@service_container]