talkfest_category_annotations:
    resource: "@EpixaTalkfestBundle/Controller/CategoryController.php"
    type:     annotation

talkfest_post_annotations:
    resource: "@EpixaTalkfestBundle/Controller/PostController.php"
    type:     annotation

talkfest_comment_annotations:
    resource: "@EpixaTalkfestBundle/Controller/CommentController.php"
    type:     annotation